#!/bin/sh
set -e

STATEDIR=/var/state/dnscvsutil

case "$1" in
        purge)
                [ -d "$STATEDIR/domains" ] && rm -rf "$STATEDIR/domains"
                [ -d "$STATEDIR/compiled" ] && rm -rf "$STATEDIR/compiled"
		chown -R root.root /var/state/dnscvsutil
                groupdel dnsadmin
                ;;
        *)
                ;;
esac
